"""Volunteer roles and their training-card content. One source for 07-training-cards.pdf and the
admin's per-volunteer card. Statute cites: 62 O.S. § 868 (county referendum), 34 O.S. § 1 (five
data points, 4-of-5 match), § 3 (pamphlet), § 6 (circulator + affidavit), § 6.1 (exclusions), § 23 (felony)."""
from __future__ import annotations

# admin Circulator.role -> card key
ROLE_KEY = {"Petition Captain": "captain", "Circulator": "circulator", "Notary": "notary", "Verifier": "verifier",
            "Event Lead": "event-lead", "Data Entry": "data-entry", "Runner": "runner", "Backup": "helper"}

ROLES = [
    {"key": "captain", "title": "Petition Captain", "admin_role": "Petition Captain", "needs_registration": False,
     "summary": "You control the one official version of the petition, every print batch, every pamphlet number, and the records that prove we did this right.",
     "job": ["File the true copy of the petition (and the ballot title) with the Secretary of the County Election Board before anyone circulates; keep the file-stamped copy.",
             "Own the print run: only the frozen, filed PDF is printed; every batch is logged with its hash; pamphlets are numbered before they leave your hands.",
             "Issue pamphlets only to cleared circulators; log issue and return daily; keep the Records Log current in the admin.",
             "Watch the clock: signed pamphlets are due within 30 days of adoption; the county publishes notice and a 10-day protest window follows."],
     "rules": [("A true copy must be filed before circulation; the form follows 34 O.S. §§ 1–2.", "62 O.S. § 868(B)(1)"),
               ("Sufficiency: at least 10% of registered voters residing in the county — plan for far more.", "62 O.S. § 868(B)(2)"),
               ("Signed copies due within 30 days after adoption; file early.", "62 O.S. § 868(B)(3)"),
               ("The ballot title (≤150 words, neutral) may be filed with the true copy and is reviewed by the District Attorney within 3 days.", "62 O.S. § 868(D)"),
               ("Every pamphlet is a copy of the filed petition with signature sheets attached; nothing else counts.", "34 O.S. § 3"),
               ("Circulators must be registered Oklahoma voters; only issue to volunteers marked cleared in the admin.", "34 O.S. § 6"),
               ("A sheet with a bad affidavit or notary loses every signature on it — audit before filing.", "34 O.S. § 6.1(A)(1),(7)")],
     "never": ["Never let anyone print, edit, or photocopy their own pamphlets.", "Never issue a pamphlet to someone whose registration and training are not recorded.",
               "Never accept loose or detached sheets.", "Never wait for the last day to file."],
     "wallet": ["Filed copy first, always", "Only the frozen PDF gets printed", "Number every pamphlet; log every handoff", "Cleared circulators only", "File early — 30 days"]},

    {"key": "circulator", "title": "Circulator", "admin_role": "Circulator", "needs_registration": True,
     "summary": "You carry an official pamphlet, watch every signature go on it, and swear to that under oath. The whole sheet depends on you doing this exactly.",
     "job": ["Carry only the numbered pamphlet the Petition Captain issued to you; keep it flat, clean, and with you.",
             "Explain neutrally: signing only supports letting county voters decide; it is not a yes or no vote.",
             "Watch each signer complete one full printed line; check it before they walk away.",
             "Return the pamphlet to the Captain on schedule; sign your affidavit in front of the notary only after signatures are collected."],
     "rules": [("You must be a registered Oklahoma voter and at least 18.", "34 O.S. § 6"),
               ("Every signature on your sheet must be signed in your presence.", "34 O.S. § 6"),
               ("Signers give the five fields: legal first name, legal last name, ZIP, house number, birth month/day. Four of five must match their registration.", "34 O.S. § 1"),
               ("Only registered voters living in this county may sign; each person signs once, their own name only. Anything else is a felony.", "34 O.S. § 23; 62 O.S. § 868"),
               ("Sheets stay attached to the pamphlet; loose or detached sheets are thrown out.", "34 O.S. §§ 3, 6.1(A)(3)"),
               ("Do not fix a signer's entry yourself — the signer corrects it while present.", "34 O.S. § 6.1"),
               ("Your affidavit is sworn before a notary after collection; a missing seal, signature, commission number or expiration date voids the whole sheet.", "34 O.S. §§ 6, 6.1(A)(7)")],
     "never": ["Never collect a signature before the Captain says the filed pamphlet is ready.", "Never detach, reorder, or photocopy pages.",
               "Never fill in a signer's information after they leave.", "Never sign a blank affidavit or sign for another circulator.",
               "Never argue, pressure, or mislead anyone — step away and call the Captain."],
     "wallet": ["Watch every signature", "5 fields, MM/DD only", "Registered county voters, own name, once", "Never detach a sheet", "Affidavit after, in front of the notary"]},

    {"key": "notary", "title": "Notary", "admin_role": "Notary", "needs_registration": False,
     "summary": "Your seal is what makes a signature sheet count. A defect in the notary block voids every signature on that sheet.",
     "job": ["Notarize circulator affidavits at scheduled sessions; the circulator appears in person with the intact pamphlet.",
             "Confirm the affidavit belongs to the sheet directly in front of it and that the circulator personally witnessed those signatures.",
             "Complete every element of the notary block, then check it again before the pamphlet leaves the table.",
             "Log each affidavit (pamphlet #, sheet #, circulator, count) on the Notary Session Log."],
     "rules": [("The affidavit is sworn by the circulator before an Oklahoma notarial officer.", "34 O.S. § 6"),
               ("The notary block must show your signature and title, complete address, commission number, expiration date, and official Oklahoma seal.", "34 O.S. § 6"),
               ("Every signature on a sheet is excluded if the notary failed to sign, the seal is absent, the commission has expired, or the expiration date is missing.", "34 O.S. § 6.1(A)(7)"),
               ("Venue must read State of Oklahoma, County of Pittsburg.", "34 O.S. § 6"),
               ("The affidavit must stay attached to its signature sheet inside the pamphlet.", "34 O.S. §§ 3, 6.1(A)(3)")],
     "never": ["Never notarize an affidavit for a circulator who is not in front of you.", "Never notarize before the signatures are collected.",
               "Never let the seal run off the page or over text.", "Never accept a detached affidavit page.", "Never notarize your own circulator affidavit."],
     "wallet": ["Circulator present, sheet intact", "Sign, title, address, commission #, expiration, seal", "Venue: Oklahoma / Pittsburg", "After collection, never before", "Log every affidavit"]},

    {"key": "verifier", "title": "Verifier (Signature Audit)", "admin_role": "Verifier", "needs_registration": False,
     "summary": "You find the problems before the Election Board does. You review returned pamphlets line by line and record counts — never signer data — in the admin.",
     "job": ["Review every returned sheet against the defect codes E1–E8; count collected, questionable, and rejected lines.",
             "Check every affidavit and notary block (signature, seal, commission number, expiration date, venue).",
             "Enter counts and defect codes on the pamphlet's sheet grid in the admin; open an Issue for anything that needs the circulator or notary.",
             "Keep pamphlets intact and in numbered order; return them to the Captain's custody after review."],
     "rules": [("Four of the five data points must match the voter file; a line missing them is questionable.", "34 O.S. § 1(B)"),
               ("E1 no circulator affidavit, E3 detached sheet, E7 notary defect: the WHOLE SHEET is excluded.", "34 O.S. § 6.1(A)(1),(3),(7)"),
               ("E2 nonresident, E4 two signers on one line, E5 off the printed line, E6 wrong name/duplicate, E8 no match: that line is excluded.", "34 O.S. § 6.1(A)"),
               ("Do not alter any entry on a sheet; note it and open an Issue.", "34 O.S. § 6.1"),
               ("Signer names, addresses and birth dates stay on paper. The admin holds counts only.", "House rule")],
     "never": ["Never write on a signature sheet.", "Never type a signer's name, address or birth date into the website or a spreadsheet.",
               "Never detach pages to make review easier.", "Never photograph completed sheets."],
     "wallet": ["E1/E3/E7 kill the sheet", "4 of 5 fields must match", "Counts only — no signer data online", "Never mark a sheet", "Open an Issue"]},

    {"key": "event-lead", "title": "Event Lead", "admin_role": "Event Lead", "needs_registration": False,
     "summary": "You run a signing location: the table, the pamphlets, the people, and the paper trail.",
     "job": ["Confirm the venue's permission and hours; make sure the location and event are marked public in the admin so the map is right.",
             "Receive numbered pamphlets from the Captain, assign each to one cleared circulator, and log the handoff.",
             "Keep the table neutral and calm; de-escalate and call the Captain if anyone is aggressive.",
             "Collect every pamphlet at the end of the shift, count sheets used, and return them the same day."],
     "rules": [("Only filed, official pamphlets may be signed; a homemade sign-up sheet is worthless and confusing to voters.", "34 O.S. § 3; 62 O.S. § 868(B)(1)"),
               ("Each pamphlet is circulated by one registered-voter circulator who witnesses its signatures.", "34 O.S. § 6"),
               ("Signers must be registered voters living in this county; point others to the OK Voter Portal.", "34 O.S. § 23; 62 O.S. § 868"),
               ("Do not let voters carry a pamphlet away from the table.", "34 O.S. § 6")],
     "never": ["Never leave pamphlets unattended.", "Never let a volunteer who is not cleared circulate.", "Never mix campaign advocacy into the signing table.",
               "Never take a pamphlet home without the Captain's approval."],
     "wallet": ["Official pamphlets only", "One cleared circulator per pamphlet", "Log every handoff", "Nothing leaves the table unattended", "Same-day return"]},

    {"key": "data-entry", "title": "Data Entry (Admin)", "admin_role": "Data Entry", "needs_registration": False,
     "summary": "You keep the Petition Master current so the Captain and the public counts are right — without ever putting voter information online.",
     "job": ["Enter pamphlet issue/return dates, sheet counts, notary details, and defect codes from the Verifier's review.",
             "Keep volunteers, locations, events and contacts current; approve website sign-ups only when the Captain says so.",
             "Log filings, office visits, print batches and receipts in the Records Log the same day.",
             "Export the workbook before major milestones and keep the file with the Captain."],
     "rules": [("Counts and statuses only. No signer names, addresses, or birth dates anywhere in the system.", "House rule; 34 O.S. § 3(B) makes the paper a public record — the site is not"),
               ("Circulators are marked cleared only after the Captain verifies registration and records training.", "34 O.S. § 6"),
               ("Dates matter: the 30-day filing clock and protest window are computed from what you enter.", "62 O.S. § 868(B)(3), (C)")],
     "never": ["Never share your admin login.", "Never mark a volunteer verified or trained on your own.", "Never delete pamphlet or issue records — change status instead."],
     "wallet": ["Counts only, never voter data", "Same-day entry", "Cleared = Captain verified", "Don't delete — change status", "Guard your login"]},

    {"key": "runner", "title": "Runner / Driver", "admin_role": "Runner", "needs_registration": False,
     "summary": "You move pamphlets between the Captain, events and notaries. The chain of custody is the job.",
     "job": ["Pick up and deliver numbered pamphlets in a closed folder; count them at both ends and note the handoff.",
             "Go straight there. Pamphlets are never left in a vehicle, at home, or with someone not on the roster.",
             "Report damage, missing pages, or anything odd to the Captain immediately."],
     "rules": [("Sheets must stay attached to the pamphlet; a detached sheet is excluded.", "34 O.S. §§ 3, 6.1(A)(3)"),
               ("You are not the circulator: do not collect signatures unless you are cleared and issued a pamphlet in your own name.", "34 O.S. § 6"),
               ("Completed sheets are public records but not for photographing or posting.", "34 O.S. § 3(B); house rule")],
     "never": ["Never leave pamphlets unattended.", "Never open, sort, or remove pages.", "Never hand pamphlets to someone not on the roster."],
     "wallet": ["Closed folder, counted both ends", "Straight there, never unattended", "Never open or sort pages", "Roster people only", "Report damage at once"]},

    {"key": "helper", "title": "Event Helper / Backup", "admin_role": "Backup", "needs_registration": False,
     "summary": "You greet, answer basic questions, and keep the table moving. You do not carry a pamphlet unless you have been cleared as a circulator.",
     "job": ["Greet neighbors, explain the petition in one sentence, and direct signers to a circulator.",
             "Help people check their registration on the OK Voter Portal (their own phone, their own lookup).",
             "Hand out the volunteer sign-up info; point questions you cannot answer to the Event Lead."],
     "rules": [("Signing supports putting the question to a vote; it is not a vote for or against.", "62 O.S. § 868(H)"),
               ("Only registered county voters may sign, once, in their own name.", "34 O.S. § 23"),
               ("Only a cleared circulator witnesses signatures on a pamphlet.", "34 O.S. § 6")],
     "never": ["Never hold or carry a pamphlet.", "Never tell anyone how to vote.", "Never collect names or phone numbers except on the volunteer form."],
     "wallet": ["Greet and direct — don't circulate", "Vote-neutral language", "Registered county voters only", "Send hard questions to the lead", "No voter data collection"]},
]
ROLE_BY_KEY = {r["key"]: r for r in ROLES}
